### REGISTER USER
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "first_name": "Imron",
  "last_name": "Abdusalimov",
  "username": "imron",
  "password": "1234"
}

### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "imron",
  "password": "1234"
}

# Sardor eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTMxOGVkODVhNDJmNzAzN2U3MGJkIn0sImlhdCI6MTY4OTg1ODQ2MX0.xShSRBOXPPH5POHl1xDJQ3f1ieHHQ8lSYM805Rpzal4

# Imron eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTMxYmRkODVhNDJmNzAzN2U3MGMwIn0sImlhdCI6MTY4OTg1ODUxMX0.L_0knm5jcfLE9Hz23kK7A89x24KK7aQdkWEP0UUTw4M

### GET ME
GET http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTMxOGVkODVhNDJmNzAzN2U3MGJkIn0sImlhdCI6MTY4OTg1ODQ2MX0.xShSRBOXPPH5POHl1xDJQ3f1ieHHQ8lSYM805Rpzal4

### PATCH ME
PATCH http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiNjk2N2RhOTc3MzVmMmQzYTBiM2Q1In0sImlhdCI6MTY4OTY4NzY3OX0.su5Qd5rv4LLu4M6lMb6jd3Mih8K9KGy4hqp0SMXu7U4
Content-Type: application/json

{
  "first_name": "Usmon"
}

### DELETE ME
DELETE http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiNjk2N2RhOTc3MzVmMmQzYTBiM2Q1In0sImlhdCI6MTY4OTY4NzY3OX0.su5Qd5rv4LLu4M6lMb6jd3Mih8K9KGy4hqp0SMXu7U4
